language: python
python:
    - 2.7
    - 3.6
    - pypy
    - pypy3
matrix:
    include:
        - python: 3.7
          dist: xenial
          sudo: true

install:
    - pip install .[form,test]
    - pip install coverage coveralls zope.testrunner

script:
    - coverage run -m zope.testrunner --test-path=src -vc

notifications:
    email: false

after_success:
    - coveralls
