language: python
python:
    - 2.7
    - 3.6
    - pypy
    - pypy3
matrix:
    include:
        - python: 3.7
          dist: xenial
          sudo: true

install:
    - travis_retry pip install .[form,test] z3c.form
    - travis_retry pip install coverage coveralls tox zope.testing

script:
    - coverage run setup.py test -q

notifications:
    email: false

after_success:
    - coveralls
